---
- name: Install ISV Linux
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - block:     
       - name: Run isv-linux-role
         ansible.builtin.include_role:
           name: isv-linux-role
         when: ansible_distribution == 'RedHat'
      #rescue:
      #  - debug:
      #      msg: "Falhou"
      #  - debug:
      #      var: urlaccess
      #always:
      #  - debug:
      #      msg: "Always"