---
- name: Install ISV Linux
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - block:     
       - name: Run isv-linux-role
         ansible.builtin.include_role:
           name: isv-linux-role
         when: ansible_distribution == 'RedHat'

       - name: Run isv-aix-role
         ansible.builtin.include_role:
           name: isv-aix-role
         when: ansible_system == 'AIX'
      #rescue:
      #  - debug:
      #      msg: "Falhou"
      #  - debug:
      #      var: urlaccess
      #always:
      #  - debug:
      #      msg: "Always"