---
- name: Install ISV Linux
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    - block:
       - name: Validate if there is a firewall rule to a URL
         become: false
         ansible.builtin.uri: 
           url: https://ipinfo.io/ip
         register: urlaccess
      
       - name: Run isv-linux-role
         ansible.builtin.include_role:
           name: isv-linux-role
      #rescue:
      #  - debug:
      #      msg: "Falhou"
      #  - debug:
      #      var: urlaccess
      #always:
      #  - debug:
      #      msg: "Always"